CPP = g++
CPPFLAGS = -Wall -std=c++11


all: initializer-list-constructor.out

initializer-list-constructor.out: initializer-list-constructor.o
	$(CPP) $(CPPFLAGS) -o initializer-list-constructor.out initializer-list-constructor.o

clean:
	-rm initializer-list-constructor.out initializer-list-constructor.o