CPP = g++
CPPFLAGS = -Wall -std=c++11


all: abstract-class.out

abstract-class.out: abstract-class.o
	$(CPP) $(CPPFLAGS) -o abstract-class.out abstract-class.o

clean:
	-rm abstract-class.out abstract-class.o