CPP = g++
CPPFLAGS = -Wall -std=c++11


all: initializer-lists.out

initializer-lists.out: initializer-lists.o
	$(CPP) $(CPPFLAGS) -o initializer-lists.out initializer-lists.o

clean:
	-rm initializer-lists.out initializer-lists.o