CPP = g++
CPPFLAGS = -Wall -std=c++11


all: range-based-for.out

range-based-for.out: range-based-for.o
	$(CPP) $(CPPFLAGS) -o range-based-for.out range-based-for.o

clean:
	-rm range-based-for.out range-based-for.o