CPP = g++
CPPFLAGS = -Wall -std=c++11


all: range-checking-vector.out

range-checking-vector.out: range-checking-vector.o
	$(CPP) $(CPPFLAGS) -o range-checking-vector.out range-checking-vector.o

clean:
	-rm range-checking-vector.out range-checking-vector.o