CPP = g++
CPPFLAGS = -Wall -std=c++11


all: complex-class.out

complex-class.out: complex-class.o
	$(CPP) $(CPPFLAGS) -o complex-class.out complex-class.o

clean:
	-rm complex-class.out complex-class.o